*** Settings ***
Resource    ./login_functionality_step_definitions.robot
Metadata    Feature    Login Functionality
Metadata    Generated by    _gherkin2robotframework on 2024-01-07T09:57:07.230825_

*** Test Cases ***
User logs in with valid credentials
    Given the user is on the login page
    When the user enters valid username and password
    Then the user should be logged in successfully


